"""empty message

Revision ID: a80da3e864ef
Revises: 
Create Date: 2024-05-01 22:34:58.956223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80da3e864ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('note', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('memory_limit', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    op.add_column('users', sa.Column('photo', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'description')
    op.drop_column('users', 'photo')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'creator_id')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'memory_limit')
    op.drop_column('tasks', 'time_limit')
    op.drop_column('tasks', 'max_score')
    op.drop_column('tasks', 'note')
    # ### end Alembic commands ###
